'''
Example commands used for few-shot learning:


    command1 = 'When the guy mentions specs of the surface go, put a textbox with that information.'
    command2 = 'For each moment where the speaker is talking about learning points, add a text with bigger font and red background.'
    command3 = 'Do 2 seconds long zoom out at the beginning of the video and add shorter text with flashy shape.'
    command4 = 'Put a greeting text in the beginning.'
    command5 = 'Whenever he starts talking about the wifi, put an imaginary wifi password.'
    command6 = 'Put the price of the surface go where it is mentioned or can be seen.'
    command7 = 'Put some images of devices that can be seen in the video.'
    command8 = 'Whenever possible, put an icon that represents the scene.'
    command9 = 'Based on the current scene, add an appropriate meme.'
    command10 = 'Put a rectangle in the top left corner.'   
    command11 = 'Whenever laptop is mentioned, put a textbox on the right side of the frame.' 
    command12 = 'Zoom should start at the bottom center.'
    command13 = 'Put the textbox with greeting text at the title-like position.'
    command14 = 'I want to remove the part where I say "um" a lot.'
    command15 = 'Whenever laptop is mentioned, put a white text with a transparent background saying "laptop".'
    command16 = 'Put a rectangle in the top left corner.'
    command17 = 'The original command was: Whenever laptop is mentioned, put a textbox on the right side of the frame.'    
    command18 = 'Zoom should start at the bottom center.'
    command19 = 'Put the textbox with greeting text at the title-like position.'
    command20 = '0:07 add a text saying: introduction'
    command21 = 'in the intro, blur the background'
    command22 = 'Add an image of a cat between 5:10 and 5:20'
    command23 = 'At current time add a text saying: The video is about...'
    command24 = 'After 30 seconds zoom out to show the whole room'
    command25 = 'Add a big sign when they guy says no one actually spend four hundred dollars on a surface go'
    command26 = 'When the guy mentions specs of the surface go, put a textbox with that information.'
    command27 = 'Highlight around his hand when the guy is holding the laptop'
    command28 = 'Put a warning sign when the guy is focusing on something else than camera'
    command29 = 'Put a greeting text in the beginning.'
    command30 = 'Whenever he starts talking about the wifi, put an imaginary wifi password.'
    command31 = 'Whenever mentioned, put the specs of the surface go'
    command32 = 'Put the price of the surface go where it is mentioned or can be seen.'
    command33 = 'Do 2 seconds long zoom out at the beginning of the video and add shorter text with flashy shape.'
    command34 = '27:32 - start video where he is talking about the chicken again - end the cut when he puts chicken into the oven.'
    command35 = 'For each moment where the speaker is talking about learning points, add a text with bigger font and red background.'
    command36 = '15:20 - Animate graphics of a book and headphones to either side of subject to engage audience and emphasis point.'
    command37 = 'Whenever there is laptop seen, put a transparent star around it'


'''